srl_nokia-interfaces:interface:
  - name: ethernet-1/1
    admin-state: enable
    vlan-tagging: false
    subinterface:
    - index: 0
      type: bridged
      admin-state: enable

  - name: ethernet-1/10
    admin-state: enable
    vlan-tagging: false
    subinterface:
    - index: 0
      type: bridged
      admin-state: enable

srl_nokia-network-instance:network-instance:
  - name: bridge-1
    admin-state: enable
    type: mac-vrf
    interface:
      - name: ethernet-1/1.0
      - name: ethernet-1/10.0