updates:
  - path: "cli:/"
    value: vlan 10
  - path: "cli:/"
    value: interface Ethernet 1
  - path: "cli:/"
    value: switchport mode access
  - path: "cli:/"
    value: switchport access vlan 10
  - path: "cli:/"
    value: interface Ethernet 10
  - path: "cli:/"
    value: switchport mode trunk
  - path: "cli:/"
    value: switchport trunk allowed vlan 10
